### ISSUE TITLE
Dead links on SAL page.

### ISSUE THREAD

**Issue by Shadowen** [LemonPi/lemonpi.github.io#2]
From page http://johnsonzhong.me/sal/

http://johnsonzhong.me/sal/string/
http://johnsonzhong.me/sal/utility/
http://johnsonzhong.me/sal/graph_algo/
http://johnsonzhong.me/sal/linear/

are all dead links.

**Comment by LemonPi** [comment]
Sorry those are still in the works (I should maybe hide them for now).
Documentation is pretty tedious...

**Comment by winstonliu** [comment]
None of the links under data structures work either. Have you looked at doxygen? Might help :P

**Comment by LemonPi** [comment]
Everything under "Everything after is still under construction" is empty for now...
I'll work on it right now...

**Comment by LemonPi** [comment]
Scaffolding generated with my Autodoc tool. I tried Doxygen, but I didn't manage to get it to contort its output in the HTML format I wanted :P.
